### ISSUE TITLE
Emojis on Twitter covered by LT icon

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool-browser-addon#164]
I cannot add emojis on Twitter because the LT icon covers Twitter's emoji icon.
![2017-10-23-215348_1024x768_scrot](https://user-images.githubusercontent.com/4381288/31910894-391555da-b83f-11e7-81b7-8e7ecd0b1fee.png)

**Comment by Tamschi** [comment]
I'm getting the same issue.

You can still reach the emojis if you slowly approach the icon from the left until it's clickable, but the Language Tool indicator really should move out of the way in these cases (and also be optional in general and/or on a site-by-site).

**Comment by danielnaber** [comment]
The indicator is already optional on a site-by-site basis, just hover it and select the left "turn off" icon.

**Comment by Tamschi** [comment]
Thanks, I didn't realise that was only for the widget.

@janschreiber I ended up fixing this locally via user style (since you reported this two weeks ago), so until there's an official workaround you can use this to use the LT widget on Twitter: [Language Tool: Twitter fix](https://userstyles.org/styles/150736/language-tool-twitter-fix)

**Comment by janschreiber** [comment]
#178 addresses this problem.

**Comment by Tamschi** [comment]
It did, but Twitter's UI just changed with the new 280 character counter, so it's broken again:
![Image of a broken Language Tool/Twitter GUI, again](https://i.imgur.com/sPNF3vO.png)

The image is simulated but should match the change in 7e96d90.

**Comment by danielnaber** [comment]
Should be fixed since some time already.
