### ISSUE TITLE
Create "Javascript plugin" variant of existing browser add-on

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#220]
We have a browser add-on ([Firefox](https://addons.mozilla.org/firefox/addon/languagetool?src=external-lt-homepage), [Chrome](https://chrome.google.com/webstore/detail/languagetool/oldceeleldhonbafppcapldpdifcinji)) that attaches itself to the textareas of each page to check them. Idea: use the same code so some Javascript snippet can be added to an HTML page so the add-on's functionality is in the page even when the user has not installed the add-on.

I image it can work like this: person who develops the HTML page adds a `<script>` tag with our code and maybe optionally calls some kind of `init()` method to specify e.g. the `id`s of the textarea to be enhanced by spell checking. That's all - the user gets the functionality of our add-on, the developer doesn't have to do anything else.

To get a better understanding, please install the add-on first and see how it works: it places a small icon in the lower right corner of every textarea. User can click it to get errors. In the dialog, user can select suggestions which are then used to replace the errors in the textarea. This is exactly what this Javascript plugin (is that a good name?) should do.

Notes:

* There should be no code duplication, i.e. the add-on could should be used as is, as far as possible, i.e. we don't want a (long-term) branch with diverging code.
* The browser add-on has two ways to show the result, in an in-page popup in the DOM and in a separate area when clicking the add-on's icon in the browser bar. For this, only the in-page result dialog can be used of course.
* For users that *do* have the add-on, things should still work and the add-on should not collide with the code in the page.
* As the logic and UI already exists, I think very little code should need to be written for this. If you think I'm wrong, let us know and we need to discuss this approach in more detail first.

**Comment by neprev** [comment]
@danielnaber as i far understood, it would be an ordinary js library that is connected to the page like everyone else. She will search for textareas in the DOM and add the necessary elements to them, as well as all the necessary api for checking words and everything else. Now we need to understand - all this code will need to be written from scratch? or not? What language is the addon for the browser written?

**Comment by danielnaber** [comment]
@neprev Any update about this?

**Comment by neprev** [comment]
@danielnaber Hi, plan to do on Wednesday

**Comment by danielnaber** [comment]
Have you started already? Can you estimate how much time this might take? I'd like to know a (rough) estimate before we spend a lot of time here.

**Comment by neprev** [comment]
@danielnaber 
First of all, we can not just use the code that is in the extension. There are two options for the plugin:
1. When the extension is installed and it works
2. When there is no extension

In the first case, we need to configure the communication between the window and the extension. For example, do not initialize the connected library if an extension is installed and running. I think that there will not be much to write, but I can not say for sure. Today I will ask my colleagues about this.

In the second case (in addition to the code that is in the first), we need to initialize the library. But this will not be an extension, so it will not work with the WebExtensions API and its add-ons, so half of the methods will need to be fixed, the other half can be re-used (mostly manipulations with the DOM). Here the work can be divided into a couple of stages:
1 . Write the basic part: when initializing, go through the DOM, find the textareas, make the necessary edits, elements, hang events, configure the sending of the request to the server (some of it can be re-used, some not). A rough estimate for this stage is 10 hours
2. Since this is not an extension, we can not take advantage (for example) of the internationalization API for extensions (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization)
So, we need to write a custom functional for language capabilities
Plus, in the extension there are various settings, for which it is possible for the same reasons to write custom functionality.
To appreciate this stage, I need a description of how works the extension with all its features, functionality, api, and so on.

**Comment by danielnaber** [comment]
Hi Nikita, thanks for the estimation. Someone else is currently making major changes to the add-on, so it makes sense to wait for that. Not sure yet how long it might take.
