### ISSUE TITLE
Remind users of extension

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#46]
Let's remind users of the add-on by showing a simple marker in the textarea that the user is using right now. Maybe in the lower right corner, like this:

![textarea2](https://user-images.githubusercontent.com/857004/29958299-521c8f56-8ef2-11e7-90a2-4bfd4932a9dd.png)

When clicked, a menu should open with these options:

* "Check text" (this might be tricky, as opening the result popup like when clicking on the icon might not be possible - see [FF](https://bugzilla.mozilla.org/show_bug.cgi?id=1341126) and [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=436489))
* "Disable add-on for this site"

Old idea:
We know from our statistics that many users install the extension, but only a small fraction of them actually uses it. The reason is probably that the extension is rather invisible. There's now code in the extension that can show a reminder toolbar on top of the page. We can show that whenever the user is typing text and hasn't used LT for several days. The code will need to be commented in and the remaining TODOs will need to be fixed.
Or maybe this: http://stackoverflow.com/questions/7730577/how-to-animate-chrome-extension-icon-in-a-callback-function

**Comment by danielnaber** [comment]
See https://github.com/languagetool-org/languagetool-browser-addon/commit/b0fcdceeb4c479c9f3d6bc8c883a7d32cb243aa3#diff-0687e7c51a238fe603b4b66562eb3d7c for an example of how this might work. A much better way would of course be to show a reminder directly in the textarea where the user is typing.

**Comment by SimonPe** [comment]
Another option for me would be to have some sort configurable of inline/next to the text field, indication.
The main reason I installed this extension 2h ago, and have only used it 2~3 times is because that button is just far away, and I need to:

 - remove my hand from my keyboard.
 - click the “LT” button
 - click any suggestions
 - move back to my keyboard to fix issues without suggestions
 - continue typing
 - repeat

Having suggestions in some always visible form, will allow me to see them (even when I'm not consciously thinking about spelling/grammar) and fix things quicker, while I'm still typing, without needing to move my hands away from my keyboard.

This however will probably result in some more hits to the server, even if you rate-limit at one request every 1~2 seconds.
Dependent on how far you want to go you could display a little dialog next to a text field which asks first whether you want to enable LT, and just clicking it once will have LT enabled for that text box, with it being visible next to it as long as the textbox is focused.

These are just some brain-farts, and as I said in the beginning, I have only installed this extension earlier today (5h by the point I'm writing this).

**Comment by danielnaber** [comment]
Hi Simon, thanks for your feedback. With Chrome, you can use the add-on by keyboard, see http://forum.languagetool.org/t/new-feature-use-chrome-add-on-with-your-keyboard/2066

**Comment by danielnaber** [comment]
Current TODOs in @jellydn's branch:

- [ ] make "check" button work
- [ ] adding the marker breaks the layout (line breaks are introduced)
- [ ] make it also work for `<div contenteditable=true>`
- [ ] we need to test a lot and also document which domains have been tested

Not so important:
- [ ] "Disable" needs to be "Disable for this domain" and that needs to be saved

**Comment by danielnaber** [comment]
- [ ] no need for an extra check button: instead, when the user hovers over the main icon (the LT icon), turn that into a checkmark and on click, check the text
- [ ] make new texts translatable
- [ ] icons should not be transparent
- [ ] use https://languagetool.org/favicon.ico for the main icon (convert to PNG first)
- [ ] can there be a timeout of e.g. 100ms when moving away from the main icon so the other icons do not disappear immediately but only after that timeout?

**Comment by danielnaber** [comment]
Minor visual issue: the close button should be a bit more to the left if there's a scrollbar and it should have the same hover effect as in the popup:
![lt-close-button](https://user-images.githubusercontent.com/857004/30580248-240bf9de-9d1c-11e7-8e67-610fc76b2314.png)
