### ISSUE TITLE
Bilingual support

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool-browser-addon#75]
Writing a manual using native language is always a mix with English words (e.g. filenames, commands, error messages). At the moment LT plugin marks all foreign words to be a spell error. So probably it can be a good idea to recheck words in latin letters with English speller and mark them as an error only if they are not in  any of native and English dictionary.

**Comment by yakovru** [comment]
Or another variant - make options for Russian, Belarussian, Ukrainian: do not spellcheck words with latin letters.

**Comment by baarsrj** [comment]
Maybe better: don't spellcheck words with ONLY non-cyrillic letters...

Verzonden van mijn mobiele telefoon.

----- Bericht beantwoorden -----
Van: "yakovru" <notifications@github.com>
Aan: "languagetool-org/languagetool-browser-addon" <languagetool-browser-addon@noreply.github.com>
Onderwerp: [languagetool-org/languagetool-browser-addon] Bilingual support (#75)
Datum: vr, sep. 16, 2016 10:33

Or another variant - make options for Russian, Belarussian, Ukrainian: do not spellcheck words with latin letters.

&mdash;You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.










{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/languagetool-org/languagetool-browser-addon","title":"languagetool-org/languagetool-browser-addon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/languagetool-org/languagetool-browser-addon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yakovru in #75: Or another variant - make options for Russian, Belarussian, Ukrainian: do not spellcheck words with latin letters."}],"action":{"name":"View Issue","url":"https://github.com/languagetool-org/languagetool-browser-addon/issues/75#issuecomment-247547243"}}}

**Comment by arysin** [comment]
Ukrainian already has this implemented: https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/uk/src/main/java/org/languagetool/rules/uk/MorfologikUkrainianSpellerRule.java

**Comment by kostyfisik** [comment]
Dear all, thank you for your responses! However, your proposals are not actually a bilingual support, it is just to ignore the second language.   If there is a misspelled word in English in my Russian text - it should be marked as wrong (if it is really wrong).  Many valid words can be expected even in non-technical texts, like names of large international companies (Google, Microsoft, Apple, Times, Daily Telegraph etc.),  well-known abbreviations (USD is not checked in Russian by may be warned in other languages) and other names (in Russian the "Brent" is written in latin standing for the oil price). I believe that the list can be extended.

**Comment by kostyfisik** [comment]
e.g. most of Hi-Tech news in Russian has some English names....

**Comment by kostyfisik** [comment]
BTW, bilingual support is the default for Chrome built-in spell checker, see the screenshot. 
![screenshot from 2016-09-17 22-01-49](https://cloud.githubusercontent.com/assets/5239997/18610464/bd4f1ae4-7d25-11e6-9df7-fc66c2cfb12e.png)

**Comment by kostyfisik** [comment]
@arysin You solution looks to be very close to what I was thinking about. Is it possible to call from MorfologikUkrainianSpellerRule the English Speller to ignore only words that are present in English dictionary?  If you are interested in implementing this I will try to copy it to Russian. It can be also a good idea not to check words that consist only of letters that  have similar spelling with Cyrillic and Latin  alphabets, like  c, o, K, HA, OT,  (нет) KOTA,  etc as soon as in Russian Wiki there are a lot of examples of mixing alphabets without any good reason.

**Comment by arysin** [comment]
I don't think I'd have this for Ukrainian. Looking at Wikipedia there's
tons of non-English words written in Latin, and tons of proper names that
would not be in the dictionary. That would create too many false positives.
We already catch mixed alphabets in words, and as for Ukrainian words typed
completely with latin, I'd like to see how often it happens so I'll need to
do some research first.

**Comment by kostyfisik** [comment]
May be the best solution is to check words in latin with English spellcheck, if there are any possible corrections to the word - mark it. If the word is in English dictionary (no corrections) or completely unknown (no corrections) - ignore this.

**Comment by danielnaber** [comment]
I'm closing the issue here, please see https://github.com/languagetool-org/languagetool/issues/766 instead - it better fits LT in general, as it's not add-on specific I think.
